/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.memorygame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JButton;

import com.mycompany.memorygame.Controler.ImageController;

/**
 *
 * @author HP
 */
public class GameFrame extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/modul4";
    static final String USER = "root";
    static final String PASS = "";
    protected String user;
    public static String tempUser = "asd";

  
    private ImageController imageController;
    
    
    /**
     * Creates new form GameFrame
     */
    public GameFrame(String user) {
        initComponents();
        String[] dataset={
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\01.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\02.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\03.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\04.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\05.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\06.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\07.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\08.png",
        "src\\main\\java\\com\\mycompany\\memorygame\\Dataset\\09.png",
        };
        this.imageController = new ImageController(dataset);
  
    }

    public void setShowTime(String text){
        this.ShowTime.setText(text);
    }


    public void setRound(int round){
        try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            String sql = "UPDATE userid SET round = round + ? WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, round);
            pstmt.setString(2, tempUser);
            
            pstmt.executeUpdate();

            pstmt.close();
            conn.close();


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setHighScore(int score) {
        try {
            
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
    
            
            String selectSql = "SELECT score FROM userid WHERE username = ?";
            try (PreparedStatement selectStmt = conn.prepareStatement(selectSql)) {
                
                selectStmt.setString(1, tempUser);
    
                ResultSet resultSet = selectStmt.executeQuery();
    
                if (resultSet.next()) {
                    int currentHighScore = resultSet.getInt("score");
    
                    if (score > currentHighScore) {
                        String updateSql = "UPDATE userid SET score = ? WHERE username = ?";
                        try (PreparedStatement updateStmt = conn.prepareStatement(updateSql)) {
                            updateStmt.setInt(1, score);
                            updateStmt.setString(2, tempUser);
    
                            updateStmt.executeUpdate();
    
                            
                        }
                    } 
                } 
            }
    
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void setShowScore(int score){
        String text = Integer.toString(score);
        this.ShowScore.setText(  text );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowScore = new javax.swing.JLabel();
        ShowTime = new javax.swing.JLabel();
        MatchPanle = new javax.swing.JPanel();
        btn02 = new javax.swing.JButton();
        btn09 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();
        btn08 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        ScoreP = new javax.swing.JLabel();
        leaderBoardButton = new javax.swing.JButton();
        leaderBoardButton1 = new javax.swing.JButton();
        TimerL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ShowScore.setBackground(new java.awt.Color(0, 0, 0));
        ShowScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ShowScore.setText("0 ");
        ShowScore.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ShowTime.setBackground(new java.awt.Color(0, 0, 0));
        ShowTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ShowTime.setText("01.00");
        ShowTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MatchPanle.setBackground(new java.awt.Color(255, 255, 255));

        btn02.setForeground(new java.awt.Color(240, 240, 240));
        btn02.setMaximumSize(new java.awt.Dimension(64, 64));
        btn02.setMinimumSize(new java.awt.Dimension(64, 64));
        btn02.setPreferredSize(new java.awt.Dimension(64, 64));
        btn02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn02MouseClicked(evt);
            }
        });

        btn09.setForeground(new java.awt.Color(240, 240, 240));
        btn09.setMaximumSize(new java.awt.Dimension(64, 64));
        btn09.setMinimumSize(new java.awt.Dimension(64, 64));
        btn09.setPreferredSize(new java.awt.Dimension(64, 64));
        btn09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn09MouseClicked(evt);
            }
        });

        btn03.setForeground(new java.awt.Color(240, 240, 240));
        btn03.setMaximumSize(new java.awt.Dimension(64, 64));
        btn03.setMinimumSize(new java.awt.Dimension(64, 64));
        btn03.setPreferredSize(new java.awt.Dimension(64, 64));
        btn03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn03MouseClicked(evt);
            }
        });

        btn04.setForeground(new java.awt.Color(240, 240, 240));
        btn04.setMaximumSize(new java.awt.Dimension(64, 64));
        btn04.setMinimumSize(new java.awt.Dimension(64, 64));
        btn04.setPreferredSize(new java.awt.Dimension(64, 64));
        btn04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn04MouseClicked(evt);
            }
        });

        btn05.setForeground(new java.awt.Color(240, 240, 240));
        btn05.setMaximumSize(new java.awt.Dimension(64, 64));
        btn05.setMinimumSize(new java.awt.Dimension(64, 64));
        btn05.setPreferredSize(new java.awt.Dimension(64, 64));
        btn05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn05MouseClicked(evt);
            }
        });

        btn06.setForeground(new java.awt.Color(240, 240, 240));
        btn06.setMaximumSize(new java.awt.Dimension(64, 64));
        btn06.setMinimumSize(new java.awt.Dimension(64, 64));
        btn06.setPreferredSize(new java.awt.Dimension(64, 64));
        btn06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn06MouseClicked(evt);
            }
        });

        btn07.setForeground(new java.awt.Color(240, 240, 240));
        btn07.setMaximumSize(new java.awt.Dimension(64, 64));
        btn07.setMinimumSize(new java.awt.Dimension(64, 64));
        btn07.setPreferredSize(new java.awt.Dimension(64, 64));
        btn07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn07MouseClicked(evt);
            }
        });

        btn08.setForeground(new java.awt.Color(240, 240, 240));
        btn08.setMaximumSize(new java.awt.Dimension(64, 64));
        btn08.setMinimumSize(new java.awt.Dimension(64, 64));
        btn08.setPreferredSize(new java.awt.Dimension(64, 64));
        btn08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn08MouseClicked(evt);
            }
        });

        btn01.setForeground(new java.awt.Color(240, 240, 240));
        btn01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn01.setMaximumSize(new java.awt.Dimension(64, 64));
        btn01.setMinimumSize(new java.awt.Dimension(64, 64));
        btn01.setPreferredSize(new java.awt.Dimension(64, 64));
        btn01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn01MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MatchPanleLayout = new javax.swing.GroupLayout(MatchPanle);
        MatchPanle.setLayout(MatchPanleLayout);
        MatchPanleLayout.setHorizontalGroup(
            MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MatchPanleLayout.createSequentialGroup()
                        .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MatchPanleLayout.createSequentialGroup()
                                .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MatchPanleLayout.createSequentialGroup()
                                .addComponent(btn05, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn06, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(MatchPanleLayout.createSequentialGroup()
                        .addComponent(btn07, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn08, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn09, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MatchPanleLayout.setVerticalGroup(
            MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MatchPanleLayout.createSequentialGroup()
                        .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn05, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn06, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatchPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn08, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn07, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn09, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ScoreP.setBackground(new java.awt.Color(0, 0, 0));
        ScoreP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ScoreP.setText("Score:");
        ScoreP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        leaderBoardButton.setBackground(new java.awt.Color(51, 102, 255));
        leaderBoardButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leaderBoardButton.setForeground(new java.awt.Color(255, 255, 255));
        leaderBoardButton.setText("Profile");
        leaderBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBoardButtonActionPerformed(evt);
            }
        });

        leaderBoardButton1.setBackground(new java.awt.Color(51, 102, 255));
        leaderBoardButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leaderBoardButton1.setForeground(new java.awt.Color(255, 255, 255));
        leaderBoardButton1.setText("Leader Board");
        leaderBoardButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBoardButton1ActionPerformed(evt);
            }
        });

        TimerL.setBackground(new java.awt.Color(0, 0, 0));
        TimerL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TimerL.setText("Timer:");
        TimerL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TimerL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leaderBoardButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ScoreP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ShowScore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leaderBoardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addComponent(MatchPanle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimerL)
                    .addComponent(ShowTime)
                    .addComponent(leaderBoardButton))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreP)
                    .addComponent(ShowScore)
                    .addComponent(leaderBoardButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(MatchPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaderBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBoardButtonActionPerformed
        new LeaderBoard().setVisible(true);
    }//GEN-LAST:event_leaderBoardButtonActionPerformed

    private void leaderBoardButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBoardButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderBoardButton1ActionPerformed

    private void btn01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn01MouseClicked
        //u.evtBtn(btn01,evt,next.get(0));
        // Match m = new Match();
        // m.setBtn(btn01);
        // m.setNumberBtn(1);
        // m.setValueMatch(next.get(0));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn01MouseClicked

    private void btn08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn08MouseClicked
        // TODO add your handling code here:
        // Match m = new Match();
        // m.setBtn(btn01);
        // m.setNumberBtn(1);
        // m.setValueMatch(next.get(0));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn08MouseClicked

    private void btn07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn07MouseClicked
        // TODO add your handling code here:
        // Match m = new Match();
        // m.setBtn(btn01);
        // m.setNumberBtn(1);
        // m.setValueMatch(next.get(0));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn07MouseClicked

    private void btn06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn06MouseClicked
        // Match m = new Match();
        // m.setBtn(btn06);
        // m.setNumberBtn(6);
        // m.setValueMatch(next.get(5));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn06MouseClicked

    private void btn05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn05MouseClicked
        // Match m = new Match();
        // m.setBtn(btn05);
        // m.setNumberBtn(5);
        // m.setValueMatch(next.get(4));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn05MouseClicked

    private void btn04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn04MouseClicked
        // Match m = new Match();
        // m.setBtn(btn04);
        // m.setNumberBtn(4);
        // m.setValueMatch(next.get(3));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn04MouseClicked

    private void btn03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn03MouseClicked
        // TODO add your handling code here:
        // Match m = new Match();
        // m.setBtn(btn03);
        // m.setNumberBtn(3);
        // m.setValueMatch(next.get(2));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn03MouseClicked

    private void btn09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn09MouseClicked
        // TODO add your handling code here:
        // Match m = new Match();
        // m.setBtn(btn01);
        // m.setNumberBtn(1);
        // m.setValueMatch(next.get(0));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn09MouseClicked

    private void btn02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn02MouseClicked
        // TODO add your handling code here:
        // Match m = new Match();
        // m.setBtn(btn02);
        // m.setNumberBtn(2);
        // m.setValueMatch(next.get(1));
        // u.getMatch().add(m);
        // u.paintMatch();
        // u.match();
    }//GEN-LAST:event_btn02MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame(tempUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MatchPanle;
    private javax.swing.JLabel ScoreP;
    private javax.swing.JLabel ShowScore;
    private javax.swing.JLabel ShowTime;
    private javax.swing.JLabel TimerL;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn08;
    private javax.swing.JButton btn09;
    private javax.swing.JButton leaderBoardButton;
    private javax.swing.JButton leaderBoardButton1;
    // End of variables declaration//GEN-END:variables
}
