/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.memorygame;

import java.sql.*;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LeaderBoard extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/memorygame";
    static final String USER = "root";
    static final String PASS = "";

    private DefaultListModel<String> leaderboardModel;

    /**
     * Creates new form LeaderBoard
     */
    public LeaderBoard() {
        initComponents();

        this.setLocationRelativeTo(this);
        leaderboardModel = new DefaultListModel<>();
        leaderboard.setModel(leaderboardModel);
        updateLeaderboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leaderboardL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderboard = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leaderboardL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leaderboardL.setText("Leaderboard");
        jPanel1.add(leaderboardL, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 26, 76, 30));

        leaderboard.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(leaderboard);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 60, 160, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/memorygame/rsz_download_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    private void updateLeaderboard() {
        Connection conn = null;
        Statement stmt = null;
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "SELECT username, score FROM player ORDER BY score DESC";
            ResultSet rs = stmt.executeQuery(sql);

            leaderboardModel.clear(); // Clear existing data

            while (rs.next()) {
                String playerName = rs.getString("username");
                int playerScore = rs.getInt("score");
                String leaderboardEntry = playerName + " " + playerScore;
                leaderboardModel.addElement(leaderboardEntry);
            }

            rs.close();
        } catch (SQLException | ClassNotFoundException se) {
            se.printStackTrace();
        } finally {
            try {
                if (stmt != null)
                    stmt.close();
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }

    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> leaderboard;
    private javax.swing.JLabel leaderboardL;
}
