/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.memorygame;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;  

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/memorygame";
    static final String USER = "root";
    static final String PASS = "";
    protected String user;

    /**
     * Creates new form Login1
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginBtn = new javax.swing.JButton();
        registerLable = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();
        plsEnterDtlLable = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        enterUser = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        enterPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBtn.setBackground(new java.awt.Color(96, 211, 148));
        LoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 216, -1));

        registerLable.setText("Don't have an account?");
        getContentPane().add(registerLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(96, 211, 148));
        loginLabel.setText("Login");
        loginLabel.setMaximumSize(new java.awt.Dimension(50, 36));
        loginLabel.setMinimumSize(new java.awt.Dimension(50, 36));
        loginLabel.setPreferredSize(new java.awt.Dimension(50, 36));
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 30));

        RegisterBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(96, 211, 148));
        RegisterBtn.setText("register here");
        RegisterBtn.setBorder(null);
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        plsEnterDtlLable.setText("Welcome back!");
        getContentPane().add(plsEnterDtlLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        UserLabel.setText("Username");
        getContentPane().add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        enterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterUserActionPerformed(evt);
            }
        });
        getContentPane().add(enterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 216, -1));

        passLabel.setText("Password");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        enterPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPassActionPerformed(evt);
            }
        });
        getContentPane().add(enterPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 216, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/memorygame/Download premium vector of Vector paper frame on food pattern background by wifiseeker about pancake, food frame, cute frame design, frame cartoon, and frame 2744688.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enterPassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enterPassActionPerformed

    private void enterUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enterUserActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enterUserActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterBtnActionPerformed
        new Register().setVisible(true);
    }// GEN-LAST:event_RegisterBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginBtnActionPerformed
        try (Connection connection = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String sql = "SELECT * FROM player WHERE username = ? AND password = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, enterUser.getText());
            statement.setString(2, enterPass.getText());
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {

                JOptionPane.showMessageDialog(new JFrame(), "Login Berhasil", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                user = enterUser.getText();
                System.out.println(user);

                // new MatchGame().setVisible(true);
                new MatchGame(user).setVisible(true);
            } else if (!resultSet.next()) {
                JOptionPane.showMessageDialog(new JFrame(), "Login Gagal", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            } else if (enterUser.equals(null) || enterPass.equals(null)) {
                JOptionPane.showMessageDialog(new JFrame(), "Username dan Password harus diisi", "Error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
        }

    }// GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField enterPass;
    private javax.swing.JTextField enterUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel plsEnterDtlLable;
    private javax.swing.JLabel registerLable;
    // End of variables declaration//GEN-END:variables
}
