/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.memorygame;

import java.sql.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Profile extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/memorygame";
    static final String USER = "root";
    static final String PASS = "";
    private String loggedInUsername;
    // public static String tempUser = "asd";

    /**
     * Creates new form Profile
     */
    public Profile(String loggedInUsername) {
        initComponents();

        this.setLocationRelativeTo(this);
        this.loggedInUsername = loggedInUsername;
        updateProfile();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProfileLabel = new javax.swing.JLabel();
        ProfileName = new javax.swing.JLabel();
        ProfileScore = new javax.swing.JLabel();
        ProfileRound = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProfileLabel.setText("Profile");
        jPanel1.add(ProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        ProfileName.setText("Nama: ");
        jPanel1.add(ProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 127, -1));

        ProfileScore.setText("Highscore: ");
        jPanel1.add(ProfileScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 127, -1));

        ProfileRound.setText("Jumlah Tes: ");
        jPanel1.add(ProfileRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 127, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/memorygame/rsz_download_2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void updateProfile() {
        Connection conn = null;
        Statement stmt = null;
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();

            String sql = "SELECT username, score, round FROM player WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, loggedInUsername);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String playerName = rs.getString("username");
                int playerScore = rs.getInt("score");
                int playerRound = rs.getInt("round");

                ProfileName.setText("Nama: " + playerName);
                ProfileScore.setText("Highscore: " + playerScore);
                ProfileRound.setText("Jumlah Tes: " + playerRound);
            }

            rs.close();
        } catch (SQLException | ClassNotFoundException se) {
            se.printStackTrace();
        } finally {
            try {
                if (stmt != null)
                    stmt.close();
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }

    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JLabel ProfileName;
    private javax.swing.JLabel ProfileRound;
    private javax.swing.JLabel ProfileScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
}
