/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.memorygame;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Register extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/memorygame";
    static final String USER = "root";
    static final String PASS = "";

    /**
     * Creates new form Register1
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passLabel = new javax.swing.JLabel();
        enterPass = new javax.swing.JTextField();
        confrmPassLabel = new javax.swing.JLabel();
        confermPass = new javax.swing.JTextField();
        RegisterBtn1 = new javax.swing.JButton();
        registerLable = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        LoginBtn1 = new javax.swing.JButton();
        plsEnterDtlLable = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        enterUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passLabel.setText("Password");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        enterPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPassActionPerformed(evt);
            }
        });
        getContentPane().add(enterPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 216, -1));

        confrmPassLabel.setText("Confirm Password");
        getContentPane().add(confrmPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        confermPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermPassActionPerformed(evt);
            }
        });
        getContentPane().add(confermPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 216, -1));

        RegisterBtn1.setBackground(new java.awt.Color(96, 211, 148));
        RegisterBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterBtn1.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn1.setText("Register");
        RegisterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 216, -1));

        registerLable.setText("already have an account?");
        getContentPane().add(registerLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(96, 211, 148));
        loginLabel.setText("Register");
        loginLabel.setMaximumSize(new java.awt.Dimension(50, 36));
        loginLabel.setMinimumSize(new java.awt.Dimension(50, 36));
        loginLabel.setPreferredSize(new java.awt.Dimension(50, 36));
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 77, 24));

        LoginBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginBtn1.setForeground(new java.awt.Color(96, 211, 148));
        LoginBtn1.setText("login here");
        LoginBtn1.setBorder(null);
        LoginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        plsEnterDtlLable.setText("Hello! Please enter your detail");
        getContentPane().add(plsEnterDtlLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        UserLabel.setText("Username");
        getContentPane().add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        enterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterUserActionPerformed(evt);
            }
        });
        getContentPane().add(enterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 216, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/memorygame/Download premium vector of Vector paper frame on food pattern background by wifiseeker about pancake, food frame, cute frame design, frame cartoon, and frame 2744688.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enterPassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enterPassActionPerformed

    private void confermPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confermPassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_confermPassActionPerformed

    private void LoginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginBtn1ActionPerformed
        new Login().setVisible(true); 
    }// GEN-LAST:event_LoginBtn1ActionPerformed

    private void enterUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enterUserActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enterUserActionPerformed

    private void RegisterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterBtn1ActionPerformed
        try (Connection connection = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String sql = "INSERT INTO player(username, password, score, round) VALUES (?, ?, 0, 0)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, enterUser.getText());
            statement.setString(2, enterPass.getText());

            if (enterUser.getText().isEmpty() && enterPass.getText().isEmpty() && confermPass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Username dan Password harus diisi", "Error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            } else if (!confermPass.getText().equals(enterPass.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Password tidak sesuai", "Error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                // The following two conditions seem unnecessary. If you still need them, modify
                // accordingly.
                if (enterUser.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(new JFrame(), "Username tidak terdaftar", "Error",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if (enterPass.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(new JFrame(), "Password tidak terdaftar", "Error",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(new JFrame(), "Register Berhasil", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                statement.executeUpdate();
                new Login().setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
        }
    }// GEN-LAST:event_RegisterBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new Register1().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn1;
    private javax.swing.JButton RegisterBtn1;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField confermPass;
    private javax.swing.JLabel confrmPassLabel;
    private javax.swing.JTextField enterPass;
    private javax.swing.JTextField enterUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel plsEnterDtlLable;
    private javax.swing.JLabel registerLable;
    // End of variables declaration//GEN-END:variables
}
